var Sample_Character = (function () {
    function Sample_Character() {
        var _this = this;
        this.time = 0;
        this.delay = 0;
        this._viewPort = new egret3d.Rectangle(0, 0, window.innerWidth, window.innerHeight);
        egret3d.Egret3DDrive.requstContext3D(DeviceUtil.getGPUMode, new egret3d.Rectangle(0, 0, this._viewPort.width, this._viewPort.height), function () { return _this.init3D(); });
    }
    var d = __define,c=Sample_Character;p=c.prototype;
    p.init3D = function () {
        var _this = this;
        this._view3D = new egret3d.View3D(this._viewPort);
        this._view3D.useShadow = true;
        this._view3D.camera3D.position = new egret3d.Vector3D(0, 5, -10);
        this._cameraCtl = new egret3d.LookAtController(this._view3D.camera3D, new egret3d.Object3D());
        this._cameraCtl.setEyesLength(400);
        window.requestAnimationFrame(function () { return _this.update(); });
        egret3d.AssetsManager.getInstance().setRootURL("resource/");
        egret3d.AssetsManager.getInstance().addLoadModel("", "suoluo/hair.esm");
        egret3d.AssetsManager.getInstance().addLoadModel("", "suoluo/body.esm");
        egret3d.AssetsManager.getInstance().addLoadTexture("SkyBox/skybox_clear_f.jpg");
        egret3d.AssetsManager.getInstance().addLoadTexture("SkyBox/skybox_clear_b.jpg");
        egret3d.AssetsManager.getInstance().addLoadTexture("SkyBox/skybox_clear_l.jpg");
        egret3d.AssetsManager.getInstance().addLoadTexture("SkyBox/skybox_clear_r.jpg");
        egret3d.AssetsManager.getInstance().addLoadTexture("SkyBox/skybox_clear_u.jpg");
        egret3d.AssetsManager.getInstance().addLoadTexture("SkyBox/skybox_clear_d.jpg");
        egret3d.AssetsManager.getInstance().addLoadTexture("suoluo/suoluomen_cl.png");
        egret3d.AssetsManager.getInstance().addLoadTexture("suoluo/suoluomen_nm.jpg");
        egret3d.AssetsManager.getInstance().addLoadTexture("suoluo/suoluomen_sp.jpg");
        egret3d.AssetsManager.getInstance().addEventListener(egret3d.Event3D.EVENT_LOAD_COMPLETE, function (e) { return _this.initScene(e); });
        egret3d.AssetsManager.getInstance().startLoad();
    };
    p.initScene = function (e) {
        var sky_f = egret3d.AssetsManager.getInstance().findTexture("SkyBox/skybox_clear_f.jpg");
        var sky_b = egret3d.AssetsManager.getInstance().findTexture("SkyBox/skybox_clear_b.jpg");
        var sky_l = egret3d.AssetsManager.getInstance().findTexture("SkyBox/skybox_clear_l.jpg");
        var sky_r = egret3d.AssetsManager.getInstance().findTexture("SkyBox/skybox_clear_r.jpg");
        var sky_u = egret3d.AssetsManager.getInstance().findTexture("SkyBox/skybox_clear_u.jpg");
        var sky_d = egret3d.AssetsManager.getInstance().findTexture("SkyBox/skybox_clear_d.jpg");
        var skyTexture = new egret3d.SkyTexture(sky_f, sky_b, sky_l, sky_r, sky_u, sky_d);
        var sky = new egret3d.Sky(skyTexture);
        this._view3D.sky = sky;
        var sprherMesh = new egret3d.Mesh(new egret3d.CubeGeometry(25, 25, 25), new egret3d.TextureMaterial());
        sprherMesh.x = 120;
        sprherMesh.y = 120;
        sprherMesh.z = -120;
        var lightGroup = new egret3d.LightGroup();
        var directLight = new egret3d.DirectLight(sprherMesh.position.clone());
        directLight.position = sprherMesh.position;
        directLight.diffuse = 0xffffff;
        directLight.halfColor = 0xffffff;
        directLight.halfIntensity = 1.0;
        lightGroup.addDirectLight(directLight);
        egret3d.ShadowRender.castShadowLight = directLight;
        var planeMesh = new egret3d.Mesh(new egret3d.PlaneGeometry(10000, 10000, 1, 1, 1, 1), new egret3d.TextureMaterial());
        // var wireframeMesh: egret3d.WireframeMesh = new egret3d.WireframeMesh();
        planeMesh.material.lightGroup = lightGroup;
        planeMesh.material.repeat = true;
        planeMesh.material.shadowMapingMethod = this._shadowMaping;
        planeMesh.material.specularColor = 0xffffff;
        planeMesh.material.specularPower = 0.5;
        planeMesh.material.ambientColor = 0x00235c;
        planeMesh.material.shininess = 10.0;
        var suoluo_texture_d = egret3d.AssetsManager.getInstance().findTexture("suoluo/suoluomen_cl.png");
        var suoluo_texture_n = egret3d.AssetsManager.getInstance().findTexture("suoluo/suoluomen_nm.jpg");
        var suoluo_texture_s = egret3d.AssetsManager.getInstance().findTexture("suoluo/suoluomen_sp.jpg");
        var mesh = egret3d.AssetsManager.getInstance().findModel("suoluo/hair.esm");
        mesh.material.diffuseTexture = suoluo_texture_d;
        mesh.material.normalTexture = suoluo_texture_n;
        mesh.material.specularTexture = suoluo_texture_s;
        mesh.material.lightGroup = lightGroup;
        mesh.material.castShadow = true;
        mesh.material.ambientColor = 0x00235c;
        mesh.material.acceptShadow = true;
        mesh.material.shadowMapingMethod = this._shadowMaping;
        this._view3D.addChild3D(mesh);
        var mesh = egret3d.AssetsManager.getInstance().findModel("suoluo/body.esm");
        mesh.material.diffuseTexture = suoluo_texture_d;
        mesh.material.normalTexture = suoluo_texture_n;
        mesh.material.specularTexture = suoluo_texture_s;
        mesh.material.lightGroup = lightGroup;
        mesh.material.castShadow = true;
        mesh.material.ambientColor = 0x00235c;
        mesh.material.ambientPower = 0.0;
        mesh.material.specularPower = 5.0;
        mesh.material.shininess = 10.0;
        //mesh.material.acceptShadow = true; 
        mesh.material.shadowMapingMethod = this._shadowMaping;
        mesh.material.bothside = true;
        //var env: egret3d.SpecularEnvironmentMappingMethod = new egret3d.SpecularEnvironmentMappingMethod(skyTexture);
        //mesh.material.addDiffusePassEffectMothod(env);
        //var wireframeMesh: egret3d.WireframeMesh = new egret3d.WireframeMesh();
        //wireframeMesh.creatByMesh(mesh);
        //this._view3D.addWireframe(wireframeMesh);
        this.body = mesh;
        this._view3D.addChild3D(mesh);
        this._view3D.addChild3D(sprherMesh);
    };
    p.update = function () {
        var _this = this;
        this.timeDate = new Date();
        this.delay = this.timeDate.getTime() - this.time;
        this.time = this.timeDate.getTime();
        this._cameraCtl.update();
        this._view3D.renden(this.time, this.delay);
        window.requestAnimationFrame(function () { return _this.update(); });
    };
    return Sample_Character;
})();
egret.registerClass(Sample_Character,"Sample_Character");
//# sourceMappingURL=Sample_Character.js.map